name: blink_alarm_clock_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  provider: ^6.1.2
  dotted_border: ^2.1.0
  flutter_local_notifications: ^17.2.3
  flutter_native_splash: ^2.4.1
  sqflite: ^2.3.3+1
  cloud_firestore: ^5.4.2
  firebase_core: ^3.5.0
  firebase_storage: ^12.3.1
  fluttertoast: ^8.2.8
  rxdart: ^0.28.0
  timezone: ^0.9.4
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app.png"
  min_sdk_android: 21


#   flutter_lints: ^4.0.0


flutter_native_splash:
  color: "#2D2F41"
  image: assets/images/splash_screen.png
  android_12:
    image: assets/images/splash_screen.png
    color: "#2D2F41"




flutter:

  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: avenir
      fonts:
        - asset: assets/fonts/Avenir-Heavy.ttf
    - family: DIGI
      fonts:
        - asset: assets/fonts/DS-DIGI.TTF
    - family: Garet
      fonts:
        - asset: assets/fonts/Garet-Book.ttf