// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr_HPY8fF_kp0ErMOxZ3YDpvfgOToKqX0',
    appId: '1:954411124760:web:4dba8aee5890fd519ddb6d',
    messagingSenderId: '954411124760',
    projectId: 'blink-alarm-clock-app',
    authDomain: 'blink-alarm-clock-app.firebaseapp.com',
    storageBucket: 'blink-alarm-clock-app.appspot.com',
    measurementId: 'G-6HMH5ZYHWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTpOjeXSMTOVPu7VAbZG_osFmHx9PRDeQ',
    appId: '1:954411124760:android:e77840df21e122179ddb6d',
    messagingSenderId: '954411124760',
    projectId: 'blink-alarm-clock-app',
    storageBucket: 'blink-alarm-clock-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChagFMsWeT4p5_nGViMlR9SJ204mNaBjU',
    appId: '1:954411124760:ios:2d145fb6f154463a9ddb6d',
    messagingSenderId: '954411124760',
    projectId: 'blink-alarm-clock-app',
    storageBucket: 'blink-alarm-clock-app.appspot.com',
    iosBundleId: 'com.example.blinkAlarmClockApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChagFMsWeT4p5_nGViMlR9SJ204mNaBjU',
    appId: '1:954411124760:ios:2d145fb6f154463a9ddb6d',
    messagingSenderId: '954411124760',
    projectId: 'blink-alarm-clock-app',
    storageBucket: 'blink-alarm-clock-app.appspot.com',
    iosBundleId: 'com.example.blinkAlarmClockApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr_HPY8fF_kp0ErMOxZ3YDpvfgOToKqX0',
    appId: '1:954411124760:web:16f367cf41d2440c9ddb6d',
    messagingSenderId: '954411124760',
    projectId: 'blink-alarm-clock-app',
    authDomain: 'blink-alarm-clock-app.firebaseapp.com',
    storageBucket: 'blink-alarm-clock-app.appspot.com',
    measurementId: 'G-1301N2JRLN',
  );
}
